//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.14 at 09:57:05 PM IST 
//


package com.technocrats.fidata.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://api.rebit.org.in/FISchema/deposit}Holders"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "holders"
})
@XmlRootElement(name = "Profile")
public class Profile {

    @XmlElement(name = "Holders", required = true)
    protected Holders holders;

    /**
     * Gets the value of the holders property.
     * 
     * @return
     *     possible object is
     *     {@link Holders }
     *     
     */
    public Holders getHolders() {
        return holders;
    }

    /**
     * Sets the value of the holders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Holders }
     *     
     */
    public void setHolders(Holders value) {
        this.holders = value;
    }

}
