//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.14 at 09:57:05 PM IST 
//


package com.technocrats.fidata.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://api.rebit.org.in/FISchema/deposit}Pending"/>
 *       &lt;/sequence>
 *       &lt;attribute name="currentBalance" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="exchgeRate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="balanceDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="type" use="required" type="{http://api.rebit.org.in/FISchema/deposit}AccountType" />
 *       &lt;attribute name="branch" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="facility" use="required" type="{http://api.rebit.org.in/FISchema/deposit}SummaryFacility" />
 *       &lt;attribute name="ifscCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="micrCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="openingDate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currentODLimit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="drawingLimit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required" type="{http://api.rebit.org.in/FISchema/deposit}StatusTypes" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pending"
})
@XmlRootElement(name = "Summary")
public class Summary {

    @XmlElement(name = "Pending", required = true)
    protected Pending pending;
    @XmlAttribute(name = "currentBalance", required = true)
    protected String currentBalance;
    @XmlAttribute(name = "currency")
    protected String currency;
    @XmlAttribute(name = "exchgeRate")
    protected String exchgeRate;
    @XmlAttribute(name = "balanceDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar balanceDateTime;
    @XmlAttribute(name = "type", required = true)
    protected AccountType type;
    @XmlAttribute(name = "branch", required = true)
    protected String branch;
    @XmlAttribute(name = "facility", required = true)
    protected SummaryFacility facility;
    @XmlAttribute(name = "ifscCode", required = true)
    protected String ifscCode;
    @XmlAttribute(name = "micrCode", required = true)
    protected String micrCode;
    @XmlAttribute(name = "openingDate", required = true)
    protected String openingDate;
    @XmlAttribute(name = "currentODLimit", required = true)
    protected String currentODLimit;
    @XmlAttribute(name = "drawingLimit", required = true)
    protected String drawingLimit;
    @XmlAttribute(name = "status", required = true)
    protected StatusTypes status;

    /**
     * Gets the value of the pending property.
     * 
     * @return
     *     possible object is
     *     {@link Pending }
     *     
     */
    public Pending getPending() {
        return pending;
    }

    /**
     * Sets the value of the pending property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pending }
     *     
     */
    public void setPending(Pending value) {
        this.pending = value;
    }

    /**
     * Gets the value of the currentBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentBalance() {
        return currentBalance;
    }

    /**
     * Sets the value of the currentBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentBalance(String value) {
        this.currentBalance = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the exchgeRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchgeRate() {
        return exchgeRate;
    }

    /**
     * Sets the value of the exchgeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchgeRate(String value) {
        this.exchgeRate = value;
    }

    /**
     * Gets the value of the balanceDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBalanceDateTime() {
        return balanceDateTime;
    }

    /**
     * Sets the value of the balanceDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBalanceDateTime(XMLGregorianCalendar value) {
        this.balanceDateTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AccountType }
     *     
     */
    public AccountType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountType }
     *     
     */
    public void setType(AccountType value) {
        this.type = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranch(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryFacility }
     *     
     */
    public SummaryFacility getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryFacility }
     *     
     */
    public void setFacility(SummaryFacility value) {
        this.facility = value;
    }

    /**
     * Gets the value of the ifscCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfscCode() {
        return ifscCode;
    }

    /**
     * Sets the value of the ifscCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfscCode(String value) {
        this.ifscCode = value;
    }

    /**
     * Gets the value of the micrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMicrCode() {
        return micrCode;
    }

    /**
     * Sets the value of the micrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMicrCode(String value) {
        this.micrCode = value;
    }

    /**
     * Gets the value of the openingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpeningDate() {
        return openingDate;
    }

    /**
     * Sets the value of the openingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpeningDate(String value) {
        this.openingDate = value;
    }

    /**
     * Gets the value of the currentODLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentODLimit() {
        return currentODLimit;
    }

    /**
     * Sets the value of the currentODLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentODLimit(String value) {
        this.currentODLimit = value;
    }

    /**
     * Gets the value of the drawingLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawingLimit() {
        return drawingLimit;
    }

    /**
     * Sets the value of the drawingLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawingLimit(String value) {
        this.drawingLimit = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusTypes }
     *     
     */
    public StatusTypes getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusTypes }
     *     
     */
    public void setStatus(StatusTypes value) {
        this.status = value;
    }

}
